# Site settings
title: 
email: ja.lueth@gmail.com
description: 
page-link: ""
baseurl: "" # the subpath of your site, e.thg. /blog/
url: "http://johnathon101.github.io" # the base hostname & protocol for your site
twitter_username: johnathon102
github_username:  johnathon101

# Build settings
markdown: kramdown
